<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EM_Stamp" Id="{0e46a50c-be27-4c21-a0c4-129444272450}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_Stamp IMPLEMENTS  ITF_EM_Stamp
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EM_Stamp">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>