<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EM_Can_Supply" Id="{80e52e0b-6656-4ee1-942a-74f49012a38a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_Can_Supply IMPLEMENTS  ITF_EM_Can_Supply
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Thijs is gejoined
//Thijs is opnieuw gejoined]]></ST>
    </Implementation>
    <LineIds Name="EM_Can_Supply">
      <LineId Id="9" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>