<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EM_Filling" Id="{e31cb704-0c01-44ce-bc30-5b4bfac97888}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_Filling IMPLEMENTS  ITF_EM_Filling
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[//voor het voorbeeld]]></ST>
    </Implementation>
    <LineIds Name="EM_Filling">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>