<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EM_Turning" Id="{eaf6caee-694c-487a-bcb2-56621ab22d66}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_Turning IMPLEMENTS  ITF_EM_Turning
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EM_Turning">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>