<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EM_Machine_PackML" Id="{0ebfbf01-80d6-47a5-bb03-0f26511ecae6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_Machine_PackML IMPLEMENTS ITF_Machine
FUNCTION_BLOCK EM_Machine_PackML EXTENDS FB_PackML

VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{466f96ba-fd55-4437-9fad-643d7a9ab3be}" />
    <Folder Name="Properties" Id="{5aadb253-608a-436b-ad87-71c3bcb865e2}" />
    <Method Name="Abort" Id="{62ebf069-5aff-4599-8383-45b8dae6de2b}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Abort : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Aborting_SC" Id="{d5e0ead7-b91e-4a1f-b436-124fbccacd19}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Aborting_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Clear" Id="{8b48837e-4ac2-495f-aa4d-4e5a1a1e175d}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Clear : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Clearing_SC" Id="{7756dac4-7687-4579-853b-11ddcae8c6a1}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Clearing_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Completing_SC" Id="{738de298-d9b5-402c-bfcb-23b046e9d3ca}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Completing_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Execute_SC" Id="{a43af042-48b9-4e7a-938b-5dec621fc285}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Execute_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Hold" Id="{c0172f22-4816-4342-8b87-014481a4bb29}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Hold : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Holding_SC" Id="{5db3b452-1080-4693-9576-e96325e42109}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Holding_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Reset" Id="{1cf186ad-b4d1-454e-a93c-ca8b658d0dfa}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Reset : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Resetting_SC" Id="{62b80db1-846e-4edc-a45e-29099895ce0b}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Resetting_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{1effadea-e115-491a-b135-432a8d131edf}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Start : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Starting_SC" Id="{e5e37957-7d85-4576-8ed4-4d3edaa1350f}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Starting_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="State" Id="{78432a1a-6379-448e-aee9-f3faccad7d91}" FolderPath="Properties\">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY State : E_State_PackML
]]></Declaration>
      <Get Name="Get" Id="{a0bce5c3-c679-4d45-910d-beaf73fa1502}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Stop" Id="{5a28b1d4-c1d5-4b74-bc12-4f952e1857f1}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Stop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stopping_SC" Id="{f201191b-5340-4262-a3ac-7bc4fc3ff4f8}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Stopping_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Suspend" Id="{56d769aa-6fb1-4bc5-b12a-b8ea765c3faf}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Suspend : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Suspending_SC" Id="{a4a7ae5a-57b3-4a95-8b54-246f9aaefa92}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Suspending_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Unhold" Id="{dbb80ab5-845f-437f-a88c-f0365137f57d}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Unhold : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Unholding_SC" Id="{62545d86-42d1-4d55-8ba5-3dc3e6a5d3ea}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Unholding_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Unsuspend" Id="{945eae42-692b-4bff-bd16-f1e3d65de51f}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Unsuspend : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Unsuspending_SC" Id="{c34ece93-63a5-4f43-82a0-43e2a207f460}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Unsuspending_SC : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="EM_Machine_PackML">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Abort">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Aborting_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Clear">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Clearing_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Completing_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Execute_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Hold">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Holding_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Reset">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Resetting_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Start">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Starting_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.State.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Stop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Stopping_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Suspend">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Suspending_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Unhold">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Unholding_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Unsuspend">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="EM_Machine_PackML.Unsuspending_SC">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>