<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_DEV_DigIn" Id="{bc7953ac-0b6f-4425-b2ef-ab2e018bf601}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DEV_DigIn EXTENDS FB_DeviceBase IMPLEMENTS ITF_DigIn
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{13d3494c-b8c8-4e6e-b02d-eaa214c13190}" />
    <Folder Name="Properties" Id="{ca254db0-bea6-43ee-b1f0-eae5b45aada0}" />
    <Property Name="ActualValue" Id="{ad68ffcb-9a9b-4f28-b77f-1557373e8652}" FolderPath="Properties\">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY ActualValue : BOOL
]]></Declaration>
      <Get Name="Get" Id="{3bde900c-89d7-4d03-8deb-709b425cc65e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{777b65e8-a2be-413d-b3f0-ec0a6f65a3b2}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="FallingEdge" Id="{7df88f60-2daf-47fd-a2b4-6989ba2bf1c1}" FolderPath="Properties\">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY FallingEdge : BOOL
]]></Declaration>
      <Get Name="Get" Id="{d30aaeee-c196-4bab-b959-5c3171b67cc9}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{01bd4f37-547f-4694-a243-f65da5e0ae5b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="FB_init" Id="{221f3045-662a-4918-999f-01d281278229}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD FB_init : BOOL
VAR_INPUT
	(* if TRUE, the retain variables are initialized (warm start / cold start)*)
	bInitRetains	: BOOL;
	(* if TRUE, the instance afterwards gets moved into the copy code (online change)*)
	bInCopyCode	: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Force" Id="{b36f677b-92fd-4909-9ef7-a239f577254a}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Force : BOOL
VAR_INPUT
	ForceValue	: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ResetForce" Id="{3c603f38-d38c-4363-a9a0-eb60af1221bc}" FolderPath="Methods\">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD ResetForce : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="RisingEdge" Id="{107f28bb-cc6c-4af6-a990-dbccfb73e039}" FolderPath="Properties\">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY RisingEdge : BOOL
]]></Declaration>
      <Get Name="Get" Id="{45aca2b1-8da5-445a-984f-e86e0b3855da}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{af15c501-7f40-40ef-9f66-e2cda7d2e16a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="FB_DEV_DigIn">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_DEV_DigIn.ActualValue.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_DEV_DigIn.ActualValue.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_DEV_DigIn.FallingEdge.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_DEV_DigIn.FallingEdge.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_DEV_DigIn.FB_init">
      <LineId Id="10" Count="0" />
    </LineIds>
    <LineIds Name="FB_DEV_DigIn.Force">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_DEV_DigIn.ResetForce">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_DEV_DigIn.RisingEdge.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_DEV_DigIn.RisingEdge.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>