<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EM_Check_Weigher" Id="{6a6823f3-6323-40e7-9859-29a8a1f5b7e8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_Check_Weigher IMPLEMENTS  ITF_EM_Check_Weigher
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EM_Check_Weigher">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>