<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_UN_base" Id="{0ff46b31-ca57-435d-9419-c972abdcf761}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_UN_base
VAR
	TagName : STRING;
	Description : STRING;
	TagID : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_UN_base">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>