<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_DeviceBase" Id="{485bf89f-73f9-4b1b-aaa0-ce1339f868c9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DeviceBase
VAR
	TagName : STRING;
	Description : STRING;
	TagID : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_DeviceBase">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>