<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EM_Labeller" Id="{eadec7c7-7888-4e8b-9a8a-e945bb69f386}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_Labeller IMPLEMENTS  ITF_EM_Labeller
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EM_Labeller">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>