<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EM_OutfeedA" Id="{2864aa0f-79f4-4c15-96e2-8d7a37ae349b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_OutfeedA EXTENDS FB_Transport
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Thijs is gejoined
//Thijs is opnieuw gejoined]]></ST>
    </Implementation>
    <LineIds Name="EM_OutfeedA">
      <LineId Id="9" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>