<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_DevicesV2" Id="{274ae7ad-92b9-47e2-b334-e236e1093c9f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DevicesV2 

VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//INITIEREN

//Kleppen

//Object dat het waterpeil berekend


//Object wat een gewenst debiet kan simuleren


//Object dat de kleppen regelt

]]></ST>
    </Implementation>
    <LineIds Name="FB_DevicesV2">
      <LineId Id="9" Count="0" />
      <LineId Id="64" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="52" Count="0" />
      <LineId Id="104" Count="0" />
      <LineId Id="100" Count="0" />
      <LineId Id="99" Count="0" />
      <LineId Id="105" Count="0" />
      <LineId Id="84" Count="0" />
      <LineId Id="111" Count="0" />
      <LineId Id="28" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>